# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c5cb6b5acac16fe8a866a2b128ae1473f2995e566c13995da6e41e52aa42d7ce505ec98c97fa6bd2501fb8ec9eac4ffe8eb750d2da3eaa86acd9227fd96343c

test:
  secret_key_base: ab0f4607421a5ab168489fb733d8ec68d50ef17af03d003828da1e249495cb5a6857fdcfc05a05cee800ac73998eed41454366d57d2ec08209d5ba623fa52bac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
